### ISSUE TITLE
AttributeError: module 'pychromecast' has no attribute 'get_chromecasts_as_dict'

### ISSUE THREAD

**Issue by Chaz6** [blha303/castctrl#1]
```
$ pip3 install --user -U castctrl
Requirement already up-to-date: castctrl in ./.local/lib64/python3.5/site-packages
Requirement already up-to-date: pychromecast in ./.local/lib64/python3.5/site-packages (from castctrl)
Requirement already up-to-date: zeroconf>=0.17.7 in ./.local/lib64/python3.5/site-packages (from pychromecast->castctrl)
Requirement already up-to-date: six>=1.10.0 in ./.local/lib64/python3.5/site-packages (from pychromecast->castctrl)
Requirement already up-to-date: protobuf>=3.0.0 in ./.local/lib64/python3.5/site-packages (from pychromecast->castctrl)
Requirement already up-to-date: requests>=2.0 in ./.local/lib64/python3.5/site-packages (from pychromecast->castctrl)
Requirement already up-to-date: enum-compat in ./.local/lib64/python3.5/site-packages (from zeroconf>=0.17.7->pychromecast->castctrl)
Requirement already up-to-date: netifaces!=0.10.5 in ./.local/lib64/python3.5/site-packages (from zeroconf>=0.17.7->pychromecast->castctrl)
Requirement already up-to-date: setuptools in ./.local/lib64/python3.5/site-packages (from protobuf>=3.0.0->pychromecast->castctrl)
Requirement already up-to-date: certifi>=2017.4.17 in ./.local/lib64/python3.5/site-packages (from requests>=2.0->pychromecast->castctrl)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in ./.local/lib64/python3.5/site-packages (from requests>=2.0->pychromecast->castctrl)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in ./.local/lib64/python3.5/site-packages (from requests>=2.0->pychromecast->castctrl)
Requirement already up-to-date: idna<2.7,>=2.5 in ./.local/lib64/python3.5/site-packages (from requests>=2.0->pychromecast->castctrl)

$ castctrl --help
Traceback (most recent call last):
  File "/home/chaz/.local/bin/castctrl", line 11, in <module>
    load_entry_point('castctrl==1.1.0', 'console_scripts', 'castctrl')()
  File "/home/chaz/.local/lib/python3.5/site-packages/castctrl/castctrl.py", line 39, in main
    casts = pychromecast.get_chromecasts_as_dict()
AttributeError: module 'pychromecast' has no attribute 'get_chromecasts_as_dict'
```

**Comment by blha303** [comment]
The function I was using there was removed at the end of 2016 https://github.com/balloob/pychromecast/pull/138

I'm not going to update this program, but you can install the last commit with this function present with `pip3 install git+https://github.com/balloob/pychromecast@cda7a0c5ef804f5306be845f8ccbbc57f11e0421`
